[project]
name = "deterministic-llm-coding"
version = "1.0.0"

[quality_gates]
max_complexity = 10
max_satd_count = 0
max_entropy_score = 30
min_documentation_coverage = 80
max_dead_code_percentage = 5

[checks]
enabled = [
    "complexity",
    "satd",
    "entropy",
    "dead_code",
    "documentation",
    "provability"
]

[output]
format = "json"
verbose = true